name: tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  unit-tests:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"
      - name: Run unit tests
        run: python -B -m unittest discover -s tests/fps-highlight-editor -p "test_*.py" -v
